name: Validate Chart

on:
  push:
    paths:
      - "chart/**"
  pull_request:
    paths:
      - "chart/**"

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chartName:
          - openfaas
          - cron-connector
          - kafka-connector
          - mqtt-connector
          - nats-connector
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
      - name: Helm Lint
        working-directory: chart
        run: helm lint ${{ matrix.chartName }}

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
          - v1.16.8
          - v1.17.4
          - v1.17.17
          - v1.18.6
          - v1.18.9
          - v1.20.4
          - v1.21.1
        chartName:
          - openfaas
          - cron-connector
          - kafak-connector
          - mqtt-connector
          - nats-connector
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: lra/setup-kubeval@v1
        with:
          version: v0.16.1
      - name: Run kubeval
        env:
          KUBEVAL_SCHEMA_LOCATION: "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/"
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        working-directory: chart
        run: |
          helm template ${{ matrix.chartName }} -f ${{ matrix.chartName }}/values.yaml -n openfaas | kubeval -n openfaas --strict --ignore-missing-schemas --kubernetes-version "${KUBERNETES_VERSION#v}"